# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [master, develop, hotfix/*, feature/*]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Build ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # Variable Reference
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x]

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js 12.x
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install node dependencies, then run lint
      - name: Install node dependencies and run the linter
        run: |
          npm ci
          npm run lint

      - name: Build
        run: npm run build

      - name: Check path
        run: |
          ls -a
          pwd

      - name: Upload Build Artifact for Test job
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: /
  # Test:
  #   # Variable Reference
  #   strategy:
  #     matrix:
  #       runs-on: ubuntu-latest
  #       node-version: 12.x
  #   # Running on ubuntu-latest
  #   runs-on: ${{ matrix.runs-on }}
  #   steps:
  #     - name: Test build
  #       run: npm test
  #     # - name: Publish build
  #     #   uses: netlify/actions/cli@master
  #     #   env:
  #     #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #     #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #     #   with:
  #     #     # "gatsby build" creates "public" folder, which is what we are deploying
  #     #     args: deploy --dir=public --prod
  #     #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
